### ISSUE TITLE
 Impossible to start queen node: Queen node is not running!

### ISSUE THREAD

**Issue by Aviksaikat** [fairDataSociety/fdp-play#145]
## Summary

I'm repeatedly getting `Impossible to start queen node: Queen node is not running!` while trying to run a bee test node using `fdp-play`.  this is a server so no GUI docker option to start the queen container manually.
![image](https://github.com/fairDataSociety/fdp-play/assets/31238298/be08640a-cd09-416f-8016-20d779694d93)

## Fix
it worked after I did `fdp-play start --pull --fresh` so there is a bug with the caching mechanism ?

**Comment by tfius** [comment]
could be, experienced same problems on Windows

**Comment by tamas6** [comment]
please check if after
`npm install -g @fairdatasociety/fdp-play@latest`
`fdp-play start --pull --fresh --bee-version latest`

The issue remains
