### ISSUE TITLE
fdp-play does not install via npm

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fdp-play#47]
OS: pop-os (ubuntu)

See screenshot:

![image](https://user-images.githubusercontent.com/1554520/191923200-cecc91b5-9129-4930-9697-8a74e884245a.png)

Following instructions in readme, `fdp-play` does not start after npm install.

**Comment by IgorShadurin** [comment]
Can't reproduce

**Comment by crtahlin** [comment]
A reboot solved the issue for me.
