### ISSUE TITLE
Fix to work with Node 18

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fdp-play#91]
When I start fdp-play with this command (Node 18)

`fdp-play start --pull --fresh --fairos`

I got an error

```
✔ Network is up
✔ Blockchain node is up and listening
✖ Impossible to start queen node: other side closed
█ Failed to run command! Please check if docker daemon is running!
```

**Comment by nugaon** [comment]
Release [v2.2.0](https://github.com/fairDataSociety/fdp-play/releases/tag/v2.2.0) addresses this.
