### ISSUE TITLE
unknown flag: --network

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fdp-play#94]
We have renamed `network` flag to `ens-network` is fairOS. So running with fairOS will throw 
```
unknown flag: --network
```

**Comment by ShaunWhitee** [comment]
Do you have any information about when the issue will be resolved?

**Comment by asabya** [comment]
If you have node+npm you can clone this repo, then change https://github.com/fairDataSociety/fdp-play/blob/0ae40de30abfbc4414ee8609c3996dc077e5977a/src/utils/docker.ts#L524 to `--ens-network=play`.

Then build the project from root with `npm run build`. then run it with `node dist/index.js start --fairos`.

Please delete old fairOS-dfs docker images from your system and it should be running.

**Comment by nugaon** [comment]
Release [v2.2.0](https://github.com/fairDataSociety/fdp-play/releases/tag/v2.2.0) addresses this.
